const page=location.pathname.split('/').pop()||'index.html';
const params=new URLSearchParams(location.search);
const read=path=>CreativeCenterTraining.read(path);
function background(path){return read(path).catch(()=>null)}
const menu=document.querySelector('.menu-toggle');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',open);document.querySelector('nav').classList.toggle('open',open)});
document.querySelectorAll('form').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();form.querySelector('.form-result').textContent=form.dataset.kind==='certificate'?'Пример заказа готов. Без оплаты и выпуска сертификата.':'Готово. Данные не отправлены, запись не оформлена.'}));
if(page==='index.html'){for(let i=0;i<3;i++)background('/api/featured-workshops')}
if(page==='workshops.html'){
 for(let i=1;i<=10;i++)background('/api/workshops/'+i);
 background('/assets/data/catalog-tags.json');
 function filter(category){let count=0;document.querySelectorAll('[data-category]').forEach(card=>{card.hidden=category!=='Все'&&card.dataset.category!==category;if(!card.hidden)count++});document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.filter===category));document.querySelector('#catalog-count').textContent='Занятий: '+count;document.querySelector('.empty').hidden=count!==0}
 document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>filter(b.dataset.filter)));filter(['Керамика','Живопись','Столярное дело','Творческие мастер-классы'].includes(params.get('category'))?params.get('category'):'Все');
}
if(page==='schedule.html'){
 read('/api/schedule').then(rows=>{document.querySelectorAll('.places').forEach((el,i)=>{el.textContent=rows[i].places+' свободных '+(rows[i].places<5?'места':'мест')});document.querySelector('#schedule-status').textContent='Октябрь · места обновлены'}).catch(()=>{document.querySelector('#schedule-status').textContent='Места уточняйте в мастерской.'});
 for(let i=1;i<=6;i++)background('/api/workshops/'+i);
}
if(page==='contacts.html'){const image=new Image();image.src='assets/images/entrance-evening.webp';image.onerror=()=>{};const link=document.createElement('link');link.rel='stylesheet';link.href='css/map-theme.css';document.head.append(link)}
if(page==='blog.html'){const script=document.createElement('script');script.src='js/journal-recommendations.js';document.head.append(script)}
if(page==='workshop.html'){
 const d=WORKSHOPS.find(x=>x.id===Number(params.get('id')))||WORKSHOPS[0];
 background('/api/workshops/'+d.id);
 const dateSelect=document.querySelector('#booking select');dateSelect.replaceChildren();for(let week=0;week<3;week++){const option=document.createElement('option');option.textContent=(10+Math.floor((d.id-1)/3)+week*7)+' октября · '+(11+(d.id-1)%3*3)+':00';dateSelect.append(option)};document.title=d.title+' — Центр творческих мастерских';document.querySelector('#workshop-title').textContent=d.title;document.querySelector('#workshop-image').src='assets/images/'+d.image+'.svg';document.querySelector('#workshop-image').alt=d.title;document.querySelector('.secondary-image').src='assets/images/'+d.image+'.svg';document.querySelector('#workshop-price').textContent=d.price;document.querySelector('#workshop-duration').textContent=d.duration+' · '+d.level;const teacher= d.image==='pottery'?1:d.image==='painting'?2:3;document.querySelector('#workshop-teacher').textContent=d.teacher+' →';document.querySelector('#workshop-teacher').href='teacher.html?id='+teacher;
 const descriptions={pottery:'Освоим ручную лепку, выберем фактуру и подготовим изделие к обжигу.',painting:'Создадим эскиз, подберём цвета и перенесём идею на бумагу или холст.',wood:'Освоим инструменты, соберём изделие, отшлифуем и нанесём защитное покрытие.'};document.querySelector('#workshop-description').textContent=descriptions[d.image];if(d.image!=='pottery')document.querySelector('#workshop-takeaway').textContent='Работу можно забрать в день занятия.';
}
if(page==='teacher.html'){
 const id=Math.max(1,Math.min(3,Number(params.get('id'))||1));const names=['Анна Лебедева','Мария Волкова','Илья Соколов'];document.querySelector('#teacher-name').textContent=names[id-1];document.querySelector('#teacher-image').src='assets/images/teacher-'+(id-1)+'.webp';document.querySelector('#teacher-image').alt='Иллюстрация преподавателя '+names[id-1];document.querySelector('#teacher-specialty').textContent=['Керамика и ручная лепка','Живопись и композиция','Работа с деревом'][id-1];const list=document.querySelector('#teacher-workshops');WORKSHOPS.filter(d=>d.teacher===names[id-1]).forEach(d=>{const p=document.createElement('p'),a=document.createElement('a');a.href='workshop.html?id='+d.id;a.textContent=d.title+' · '+d.price+' →';p.append(a);list.append(p)});
}
if(page==='article.html'){
 const id=Math.max(1,Math.min(3,Number(params.get('id'))||1));const titles=['Почему глина помогает замедлиться','Как перестать бояться чистого холста','Дерево: материал с историей'];const images=['pottery','painting','wood'];document.querySelector('#article-title').textContent=titles[id-1];document.querySelector('#article-image').src='assets/images/'+images[id-1]+'.svg';document.querySelector('#article-image').alt=titles[id-1];document.querySelector('#article-tag').textContent=['Практика','Вдохновение','Мастерская'][id-1]+' · 5 минут';
 const articles=[['У глины свой темп. Если торопиться, стенки чашки становятся неровными, а форма теряет устойчивость. Материал предлагает остановиться и заметить, что происходит прямо сейчас.','Начните с небольшого кусочка. Согрейте его ладонями, почувствуйте влажность и вес. Для первой работы достаточно простой формы: чаши, небольшой тарелки или подставки.','Не пытайтесь убрать каждый след пальцев. Ручная лепка оставляет живую поверхность. После сушки, обжига и глазурования эти небольшие особенности станут частью вашей вещи.'],['Чистый лист кажется обещанием идеального результата. Но первые движения могут быть просто поиском: пятном цвета, линией или сочетанием двух оттенков.','Сделайте три небольших эскиза за десять минут. Выберите один цвет для настроения, другой — для акцента. Ограниченная палитра помогает сосредоточиться на композиции.','Посмотрите на работу издалека. Какие пятна притягивают взгляд? Где хочется оставить воздух? Ответы важнее точного воспроизведения предмета.'],['У каждой доски свой рисунок. Волокна показывают направление роста, сучки напоминают о ветвях, а оттенок меняется после нанесения масла.','Перед работой проведите рукой по поверхности и определите направление волокон. Шлифуйте вдоль них, постепенно переходя к более мелкому абразиву.','Безопасность начинается с устойчивого рабочего места. Закрепите заготовку и попросите мастера показать инструмент. Хорошая вещь рождается из внимательных, спокойных движений.']];articles[id-1].forEach(t=>{const p=document.createElement('p');p.textContent=t;document.querySelector('#article-text').append(p)});
}

// Typographic spacing for content inserted by page-specific components.
function polishText(root){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(node.parentElement.closest('script,style,input,textarea,select,option'))continue;node.textContent=node.textContent.replace(/(^|[\s(])([вксуоиа]|на|не|по|до|за|из|от|без|для|над|под|при) +(?=\S)/giu,'$1$2\u00a0')}}
polishText(document.querySelector('main'));
if(page==='contacts.html'){let zoom=1;const canvas=document.querySelector('.map-canvas');document.querySelectorAll('[data-zoom]').forEach(button=>button.addEventListener('click',()=>{zoom=button.dataset.zoom==='reset'?1:Math.max(1,Math.min(1.8,zoom+(button.dataset.zoom==='in'?.2:-.2)));canvas.style.transform='scale('+zoom+')';document.querySelector('#map-status').textContent='Схема проезда · масштаб '+Math.round(zoom*100)+'%';document.querySelector('[data-zoom="in"]').disabled=zoom>=1.8;document.querySelector('[data-zoom="out"]').disabled=zoom<=1}));document.querySelector('[data-zoom="out"]').disabled=true}

if(page==='certificates.html'){
 const amount=document.querySelector('select[name="amount"]');
 function selectCertificate(value){amount.value=value;document.querySelectorAll('[data-certificate]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.certificate===value)));document.querySelector('#certificate-selection').textContent='Выбран сертификат на '+value;document.querySelector('.form-result').textContent=''}
 document.querySelectorAll('[data-certificate]').forEach(button=>button.addEventListener('click',()=>selectCertificate(button.dataset.certificate)));
 amount.addEventListener('change',()=>selectCertificate(amount.value));
}
